// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.8
// source: proto/containerly.proto

package containerly

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ContainerlyClient is the client API for Containerly service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ContainerlyClient interface {
	Service(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type containerlyClient struct {
	cc grpc.ClientConnInterface
}

func NewContainerlyClient(cc grpc.ClientConnInterface) ContainerlyClient {
	return &containerlyClient{cc}
}

func (c *containerlyClient) Service(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/containerly.Containerly/Service", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ContainerlyServer is the server API for Containerly service.
// All implementations must embed UnimplementedContainerlyServer
// for forward compatibility
type ContainerlyServer interface {
	Service(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedContainerlyServer()
}

// UnimplementedContainerlyServer must be embedded to have forward compatible implementations.
type UnimplementedContainerlyServer struct {
}

func (UnimplementedContainerlyServer) Service(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Service not implemented")
}
func (UnimplementedContainerlyServer) mustEmbedUnimplementedContainerlyServer() {}

// UnsafeContainerlyServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ContainerlyServer will
// result in compilation errors.
type UnsafeContainerlyServer interface {
	mustEmbedUnimplementedContainerlyServer()
}

func RegisterContainerlyServer(s grpc.ServiceRegistrar, srv ContainerlyServer) {
	s.RegisterService(&Containerly_ServiceDesc, srv)
}

func _Containerly_Service_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContainerlyServer).Service(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/containerly.Containerly/Service",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContainerlyServer).Service(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// Containerly_ServiceDesc is the grpc.ServiceDesc for Containerly service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Containerly_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "containerly.Containerly",
	HandlerType: (*ContainerlyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Service",
			Handler:    _Containerly_Service_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/containerly.proto",
}
